export const api = {
    apiHeaderForGuest:{
        "Content-Type": "application/json",
    },
    base: "http://localhost:5001",
    media_path: "https://storage.cloud.google.com/mliki-nftmarketplace/media",
    connect: "/user/connect",
    user_profile: "/user/profile",
    user_update: "/user/update",
    user_verfiy: "/user/verify",
    user_confirm: "/user/confirm",
    user_views: "/user/views",
    user_notifications: "/user/notifications",
    user_updatenotification: "/user/updatenotification",
    seller_list: "/user/list",
    search_result: "/user/search",
    follow_action: "/connection",
    collection_add: "/collection/add",
    collection_update: "/collection/update",
    collection_list: "/collection/list",
    collection_all_list: "/collection/alllist",
    collection_detail: "/collection/detail",
    collection_delete: "/collection/delete",
    collection_abi: "/collection/generateabi",
    collection_update_approval: "/collection/updateapprovals",
    collection_check_approval: "/collection/checkapproval",
    category_list: "/category/list",
    item_add: "/item/add",
    item_sell: "/item/sell",
    item_removesale: "/item/removesale",
    item_update: "/item/update",
    item_update_offer: "/item/updateoffer",
    item_delete: "/item/delete",
    item_list: "/item/list",
    item_add_like: "/item/addfavourites",
    item_add_view: "/item/addviews",
    item_moreFromCollection: "/item/moreFromCollection",
    item_purchase: "/item/purchase",
    item_history: "/item/history",
    item_prices:"/item/prices",
    item_offers: "/item/offers",
    item_add_offers: "/item/addoffer",
    item_remove_offers: "/item/removeoffer",
    item_action_offers: "/item/actionoffer",

    option_get: "/admin/getoptions",

    royalty_delete: "/collection/deleteroyalty",
    royalty_add: "/collection/addroyalty",
    royalty_get: "/collection/checkroyalty",
    banner_list: "/slider/list",
    item_csv: "/item/save-csv",
    deposits: "/item/deposits",
    withdraw: "/item/withdraw",
    faq_list: "/settings/faqs",
    item_already_bid: "/item/check-offer",
    token_info: "/item/token-info"
}
